### PR TITLE
fix issue #13

### PR DESCRIPTION
**Pull request by Lotterleben**
hopefully

### CODE REVIEW

**Comment by pv0** [comment]
Happy with this change, not entirely sure what issue 13 was anyway though...

**Comment by Lotterleben** [comment]
https://github.com/Lotterleben/AODVv2-Draft/issues/13 ^^TL; DR: we decided to make clear that others may define other, non-cost metrics, but it's out of the scope of the draft to tell you how.

**Comment by Lotterleben** [comment]
But: yay :) Any Vetos, @charliep51 @ratliffstan ? If not I'd like to merge this then.

**Comment by Lotterleben** [comment]
For the record: @charliep51 said that he's happy with the changes in google hangouts :)

**Comment by Lotterleben** [comment]
Again, no veto from @ratliffstan in 7 days, merging this now, please shout at me if that was premature

**Pull request merged**
